### ISSUE TITLE
package is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by pschuele** [geerlingguy/ansible-role-redis#14]
When using the current master (https://github.com/geerlingguy/ansible-role-redis/commit/a76cee52f0f4a9e33493ea333e1f7265b148dac6) of ansible-role-redis, I get this error (with ansible 1.9.4):

ERROR: package is not a legal parameter in an Ansible task or handler

I reverted to tag 1.3.0 and it works again.

Maybe the master only works with ansible 2+?

Thanks for providing this role :)

**Comment by geerlingguy** [comment]
Eek, you're correct! I forgot to bump the required version in the last tag. Sorry about that (see: https://github.com/geerlingguy/ansible-role-redis/blob/master/meta/main.yml#L9).

I'll do that now.

**Comment by geerlingguy** [comment]
Fixed: https://github.com/geerlingguy/ansible-role-redis/commit/f457d0c4f27ddda817b13cde69673ac1e3a1dd35

**Comment by mojili** [comment]
just upgrade ansible from 1.5.4 to 2.3.0 

$ sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible
$ sudo apt-get update
$ sudo apt-get install ansible

and get successful response. (package module has been newly added to version 2 as I checked)

**Comment by amritsql** [comment]
@mojili your steps saved a lot of time

**Comment by sushil2226** [comment]
@mojili  works , thanks

**Comment by vinoddharani** [comment]
@mojili thank you soo much it works.
