### ISSUE TITLE
How is defined ansible_os_family?

### ISSUE THREAD

**Issue by braveadmin** [geerlingguy/ansible-role-redis#19]
in the main inside tasks there is a include_vars: "{{ ansible_os_family }}.yml"
but i can't find this variable anywhere and indeed the deploy is failing. 
where can i find it?

many thanks

**Comment by geerlingguy** [comment]
@braveadmin - That is one of Ansible's global vars that's set up during the 'gather_facts' operation. Do you have `gather_facts: no` in your playbook? If so, that variable may never be set.

Also, what's the specific error you're getting? It could be something else too...

**Comment by braveadmin** [comment]
Thanks Geerling, the problem was solved with gather_facts variable, i just forgot to respond :)

**Comment by geerlingguy** [comment]
Awesome!
