### ISSUE TITLE
i am ruuning my ansible code i got this error

### ISSUE THREAD

**Issue by Madhav1217** [geerlingguy/ansible-role-redis#31]
fatal: [13.127.200.142]: FAILED! => {"failed": true, "msg": "Unable to create local directories(/home/ubuntu/.ansible/cp): [Errno 13] Permission denied: '/home/ubuntu/.ansible/cp'"}

**Comment by geerlingguy** [comment]
It looks like this is a problem with your permissions for your user account; can you do anything with Ansible playbooks? I would suggest opening an issue or asking a question in a broader forum, like the Ansible Project mailing list on Google Groups, or on stack exchange. You will need to list out what kind of playbook you were running it, where you were running it, more playbook output (e.g. what task actually failed), etc.

**Comment by sprashanthraj** [comment]
"msg": "Unable to create local directories(/home/ubuntu/.ansible/cp): [Errno 13] Permission denied: '/home/ubuntu/.ansible/cp'"

I have the same issue while i am trying to ping the node from Ansible server

**Comment by sprashanthraj** [comment]
well,  i dint run any YML file, before that i am struck with this issue.

**Comment by sprashanthraj** [comment]
[WARNING]: Unable to set correct type for configuration entry: DEFAULT_LOCAL_TMP

 [WARNING]:  * Failed to parse /etc/ansible/hosts with yaml plugin: Syntax Error while loading YAML.   did not find expected <document start>  The error
appears to have been in '/etc/ansible/hosts': line 21, column 1, but may be elsewhere in the file depending on the exact syntax problem.  The offending line
appears to be:  [client] Node1 172.31.19.69 ^ here

 [WARNING]:  * Failed to parse /etc/ansible/hosts with ini plugin: /etc/ansible/hosts:21: Expected key=value host variable assignment, got: 172.31.19.69

 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

 [WARNING]: Could not match supplied host pattern, ignoring: 172.31.19.69
