### ISSUE TITLE
Add redis_install_from_source option

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-redis#4]
Add an option to install Redis from source (so users can have the latest possible version, instead of just the versions available through the default apt repos or EPEL).

**Comment by JorisVanEijden** [comment]
:+1:

**Comment by winem** [comment]
Currently working on a setup of a redis 3.x  cluster from source. So I would be glad to do this and to contribute to one of your repositories. 

@geerlingguy I would use a default variable that installs Redis from the repositories and includes a new task setup-from-Source.yml if you override the default. Do you have any comments on this approach?

**Comment by geerlingguy** [comment]
@winem - Would love to see it! Check out these two roles for examples of how I did it there:

  - https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/install-from-source.yml
  - https://github.com/geerlingguy/ansible-role-git/blob/master/tasks/install-from-source.yml (simpler example)

**Comment by winem** [comment]
@geerlingguy finally, I have had time to come back this issue and created a new task file. Will create the PR soon. 

Please note, that I added some new variables. All, except for reidis_multiple_instances are related to the manual build of ansible. redis_multiple_instances becomes important if you want to run more than one instance on a single server. We use this for slaves for example. So, I will add a new "feature" to configure redis as slave to a master and to run multiple instances on a single host soon.

**Comment by tersmitten** [comment]
You also might want to have a look at https://github.com/Oefenweb/ansible-redis
