### ISSUE TITLE
'vm-enabled no' startup error.

### ISSUE THREAD

**Issue by thom-nic** [geerlingguy/ansible-role-redis#5]
I'm seeing the same issue as those reported here:
https://github.com/bennojoy/redis/issues/6

Shell output:
```
$ redis-server --version
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9

$ sudo redis-server /etc/redis/redis.conf 

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 34
>>> 'vm-enabled no'
Bad directive or wrong number of arguments
```

**Comment by geerlingguy** [comment]
Thanks for reporting! I was testing on a server with Redis 2.4.14, so that's why I didn't get hit with this error. Since VM use was discouraged even in 2.4, I decided to just remove that chunk of configuration entirely.

**Comment by thom-nic** [comment]
This appears to break in redis 2.8 as well:

```
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
```
The `zipmap` options apparently replace that, which you have below in the file.

Super annoying that redis doesn't silently ignore these :sob:

**Comment by geerlingguy** [comment]
> Super annoying that redis doesn't silently ignore these

Yeah :/

Can you open a new issue for that?

**Comment by thom-nic** [comment]
Done. #6
