### ISSUE TITLE
hash-map-zipmap config causes redis 2.8 to bail

### ISSUE THREAD

**Issue by thom-nic** [geerlingguy/ansible-role-redis#6]
These items in the redis config template break under redis 2.8:

```
hash-max-zipmap-entries 512
hash-max-zipmap-value 64
```
They have been replaced with `hash-max-ziplist-*` which it appears you already have in the config.
http://redis.io/topics/memory-optimization.

**Comment by geerlingguy** [comment]
Hopefully the above commit fixes this. I'm going to wait for Travis test confirmation before releasing a new version on Galaxy.

**Comment by thom-nic** [comment]
Thanks for the quick response!
