### ISSUE TITLE
Explicitly disable RDB persistence

### ISSUE THREAD

**Issue by rsanzante** [geerlingguy/ansible-role-redis#73]
Doc says: 

"# Set to an empty set to disable persistence (saving the DB to disk)."

So, when setting:

```
redis_save: []
```

However, this just writes nothing about the Redis  "save" settings. If for whatever reason RDB persistence is enabled by default this role won't disable it.

**Comment by rsanzante** [comment]
This issue  is still active. I can provide more info ro work if needed.

**Comment by nicovs** [comment]
Just add:
`
redis_save:
  - '""'
`

**Comment by rsanzante** [comment]
Not very intuitive but nice to know, thanks!
